from srim import TRIM, Ion, Layer, Target
import os

# Path to your SRIM installation
SRIM_DIR = "/Users/cbharathulwar/Documents/Research/Walsworth/SRIM-2013"

# --- Define ion and target ---
ion = Ion("C", energy=50e3)  # 50 keV carbon ion
layer = Layer({"C": 1.0}, density=3.51, width=2e4)  # diamond-like target
target = Target([layer])

# --- Configure and run TRIM ---
trim = TRIM(
    target=target,
    ion=ion,
    number_ions=10,
    calculation=2,  # Full cascade
    output_dir="srim_out_50keV_test"
)

# Run SRIM (TRIM.IN is auto-generated by PySRIM)
trim.run(srim_directory=SRIM_DIR)

print("✅ SRIM full-cascade test complete. COLLISIONS.txt should be generated.")